// Generated by gitlab-spec-tool — do not edit.
// Conforms every filtered entity that has an `id` to Identifiable, so the review
// entities drop into SwiftUI `ForEach`/`List`. The `id` is optional only because
// GitLab marks few response fields required; real payloads always carry it.

import GitLabOpenAPI

extension Components.Schemas.APIEntitiesAnalyticsCodeReviewMergeRequest: Identifiable {}
extension Components.Schemas.APIEntitiesApprovalRuleShort: Identifiable {}
extension Components.Schemas.APIEntitiesApprovalState: Identifiable {}
extension Components.Schemas.APIEntitiesAwardEmoji: Identifiable {}
extension Components.Schemas.APIEntitiesCiPipeline: Identifiable {}
extension Components.Schemas.APIEntitiesCiPipelineBasic: Identifiable {}
extension Components.Schemas.APIEntitiesCommit: Identifiable {}
extension Components.Schemas.APIEntitiesCommitDetail: Identifiable {}
extension Components.Schemas.APIEntitiesCommitStatus: Identifiable {}
extension Components.Schemas.APIEntitiesDiscussion: Identifiable {}
extension Components.Schemas.APIEntitiesDraftNote: Identifiable {}
extension Components.Schemas.APIEntitiesGroup: Identifiable {}
extension Components.Schemas.APIEntitiesGroupApprovalRule: Identifiable {}
extension Components.Schemas.APIEntitiesMergeRequest: Identifiable {}
extension Components.Schemas.APIEntitiesMergeRequestApprovalRule: Identifiable {}
extension Components.Schemas.APIEntitiesMergeRequestApprovalStateRule: Identifiable {}
extension Components.Schemas.APIEntitiesMergeRequestBasic: Identifiable {}
extension Components.Schemas.APIEntitiesMergeRequestChanges: Identifiable {}
extension Components.Schemas.APIEntitiesMergeRequestDependency: Identifiable {}
extension Components.Schemas.APIEntitiesMergeRequestDiff: Identifiable {}
extension Components.Schemas.APIEntitiesMergeRequestDiffFull: Identifiable {}
extension Components.Schemas.APIEntitiesMergeRequestSimple: Identifiable {}
extension Components.Schemas.APIEntitiesMergeTrainsCar: Identifiable {}
extension Components.Schemas.APIEntitiesMilestone: Identifiable {}
extension Components.Schemas.APIEntitiesNote: Identifiable {}
extension Components.Schemas.APIEntitiesProjectApprovalRule: Identifiable {}
extension Components.Schemas.APIEntitiesProjectApprovalSettingRule: Identifiable {}
extension Components.Schemas.APIEntitiesProtectedBranch: Identifiable {}
extension Components.Schemas.APIEntitiesProtectedRefAccess: Identifiable {}
extension Components.Schemas.APIEntitiesSuggestion: Identifiable {}
extension Components.Schemas.APIEntitiesTreeObject: Identifiable {}
extension Components.Schemas.APIEntitiesUserBasic: Identifiable {}
